#### Import of the Packages

In [1]:
import torch
import numpy as np
import session_info
session_info.show()

##### Verify if GPU can be used

In [2]:
torch.cuda.is_available()

True

##### Create empty tensor

In [3]:
x= torch.empty(3,2)
print(x)

tensor([[1.0286e-38, 8.9081e-39],
        [8.9082e-39, 7.5306e-39],
        [8.9082e-39, 9.6429e-39]])


##### Create random tensor

In [4]:
y= torch.rand(2,2)
print(y)

tensor([[0.6600, 0.9830],
        [0.2853, 0.5928]])


##### Create tensor full of zeros /ones

In [5]:
x= torch.zeros(2,3,6)
print(x)
y=torch.ones(3,1,3, dtype= torch.int)
print(y)

tensor([[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]])
tensor([[[1, 1, 1]],

        [[1, 1, 1]],

        [[1, 1, 1]]], dtype=torch.int32)


##### Operation on tensors

In [6]:
x= torch.rand(2,2)
y= torch.rand(2,2)

z= x+y
#is similar to
z= torch.add(x,y)
print(z)

tensor([[0.9779, 1.2583],
        [1.3583, 0.7016]])


In [7]:
y.add_(x) # Note: In Pytorch, function with underscore correspond to an inplace function
print(y)
y.mul_(x)

tensor([[0.9779, 1.2583],
        [1.3583, 0.7016]])


tensor([[0.5584, 0.9059],
        [1.0612, 0.4524]])

##### Select columns/rows of tensors

In [8]:
x= torch.rand(5,3)
print(x)
print(x[:,0]) # selection of the first column
print(x[1,:]) # selection of the second row 
print(x[2,2]) # selection of one element
print(x[2,2].item()) # get the value (only on one element)

tensor([[0.1081, 0.7926, 0.8133],
        [0.3318, 0.1130, 0.6132],
        [0.4029, 0.8732, 0.6838],
        [0.4997, 0.1028, 0.0939],
        [0.4707, 0.9919, 0.3885]])
tensor([0.1081, 0.3318, 0.4029, 0.4997, 0.4707])
tensor([0.3318, 0.1130, 0.6132])
tensor(0.6838)
0.6837839484214783


#### Reshape tensor

In [9]:
x= torch.rand(4,5)
y=x.view(20) # number of element must be the same than x
z=x.view(-1,2) # -1 attribute the dimension in function of the other given values
print(y)
print(z)

tensor([0.8857, 0.2254, 0.1286, 0.9790, 0.2509, 0.8937, 0.5554, 0.7188, 0.6950,
        0.3310, 0.5618, 0.1343, 0.6149, 0.7093, 0.0224, 0.3099, 0.3061, 0.9688,
        0.8415, 0.3088])
tensor([[0.8857, 0.2254],
        [0.1286, 0.9790],
        [0.2509, 0.8937],
        [0.5554, 0.7188],
        [0.6950, 0.3310],
        [0.5618, 0.1343],
        [0.6149, 0.7093],
        [0.0224, 0.3099],
        [0.3061, 0.9688],
        [0.8415, 0.3088]])


#### Tranform np.array into tensor and vice-versa

In [10]:
x= torch.zeros(2,3)
y=x.numpy() # note that x and y share the same memory location and a modificationof y will change x and vice-versa
print(y)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
a= np.ones(4)
b= torch.from_numpy(a.astype(int))# astype allowing to change the dtype
print(b)

tensor([1, 1, 1, 1], dtype=torch.int32)


##### Transfer to the GPU for calculation

In [12]:
device =torch.device("cuda")
x= torch.ones(4)
y= torch.ones(4) # x and y are created on the CPU
x=x.to(device)
y=y.to(device) # x and y are transfer to the GPU
z= x+y # operation take place on the GPU
z=z.to("cpu")
print(z)

tensor([2., 2., 2., 2.])


##### Create a tensor that can be adjusted later during optimisation/Training

In [13]:
x= torch.ones(5, requires_grad= True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
